In [1]:
from sklearn.metrics import roc_auc_score
import pandas as pd
import numpy as np
import random

In [3]:
a = [random.randint(0,9) for i in range(30)]
b = [random.randint(0,1) for i in range(30)]
c = [random.random() for i in range(30)]
d = [random.random()*10 for i in range(30)]

data = {"user_id": a, "label": b, "prob": c, "label2": d}
df = pd.DataFrame(data)
df

    user_id  label      prob    label2
0         5      0  0.214364  8.950824
1         2      1  0.120766  7.555006
2         3      1  0.982898  8.479580
3         1      1  0.139504  8.765297
4         3      1  0.657827  7.444388
5         9      0  0.574108  3.960157
6         7      0  0.544058  5.108027
7         5      1  0.206598  6.177297
8         6      0  0.914994  5.103773
9         9      1  0.326907  0.425035
10        9      1  0.622911  0.263115
11        3      0  0.089987  2.220384
12        1      0  0.553020  6.119303
13        4      0  0.810042  2.457919
14        7      1  0.871479  4.745131
15        4      1  0.437074  8.935624
16        2      1  0.603093  0.090197
17        7      0  0.902751  8.435662
18        8      1  0.365610  6.433268
19        5      0  0.804445  1.418772
20        8      0  0.109568  2.301468
21        6      0  0.121732  6.055005
22        5      0  0.041135  1.487878
23        2      1  0.462474  3.927155
24        7      0  0.026727  6.393491
25        4      0  0.026150  4.122620
26        4      0  0.749089  3.441709
27        6      1  0.446638  3.408277
28        4      0  0.081538  1.204404
29        2      1  0.387258  3.788925

In [7]:
def gauc(df, is_spearmanr = True):
  df_temp = df.groupby(['user_id'])
  roc = 0
  impression = 0
  for key, value in df_temp:
    if value.size <=1 or len(list(value.iloc[:, 1].unique())) <=1:
      continue
    else:
      if is_spearmanr:
        auc = roc_auc_score(value.iloc[:, 1], value.iloc[:, 2])
      else:
        _, auc = auc_custom(value.iloc[:, 1].tolist(), value.iloc[:, 2].tolist())
      
      roc += value.size * auc
      impression += value.size
  return roc / impression

def reversePairs(data):
    ans = 0
    prefix = []
    for n in data:
        left, right = 0, len(prefix)
        while left < right:
            mid = (left + right) // 2
            if n >= prefix[mid]:
                left = mid + 1
            else:
                right = mid
        ans += len(prefix) - left
        prefix[left:left] = [n]
    return ans

def auc_custom(labels, probs):
  
  n = len(labels)
  f = list(zip(probs, labels))

  rank_pos = [values2 for values1, values2 in sorted(f, key=lambda x: x[0], reverse=True)]
  pos_num = reversePairs(rank_pos)

  auc = pos_num / (n * (n - 1) / 2)

  return pos_num, auc

In [8]:
gauc(df[["user_id", "label", "prob"]])

0.5576923076923077

In [9]:
gauc(df[["user_id", "label2", "prob"]], is_spearmanr = False)

0.45555555555555555